// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::update_config_type::UpdateConfig;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `update_config`.
///
/// Obtain a handle from the [`UpdateConfigTableAccess::update_config`] method on [`super::RemoteTables`],
/// like `ctx.db.update_config()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.update_config().on_insert(...)`.
pub struct UpdateConfigTableHandle<'ctx> {
    imp: __sdk::TableHandle<UpdateConfig>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `update_config`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UpdateConfigTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UpdateConfigTableHandle`], which mediates access to the table `update_config`.
    fn update_config(&self) -> UpdateConfigTableHandle<'_>;
}

impl UpdateConfigTableAccess for super::RemoteTables {
    fn update_config(&self) -> UpdateConfigTableHandle<'_> {
        UpdateConfigTableHandle {
            imp: self.imp.get_table::<UpdateConfig>("update_config"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UpdateConfigInsertCallbackId(__sdk::CallbackId);
pub struct UpdateConfigDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UpdateConfigTableHandle<'ctx> {
    type Row = UpdateConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UpdateConfig> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UpdateConfigInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UpdateConfigInsertCallbackId {
        UpdateConfigInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UpdateConfigInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UpdateConfigDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UpdateConfigDeleteCallbackId {
        UpdateConfigDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UpdateConfigDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UpdateConfig>("update_config");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UpdateConfig>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UpdateConfig>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `update_config`,
/// which allows point queries on the field of the same name
/// via the [`UpdateConfigIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.update_config().id().find(...)`.
pub struct UpdateConfigIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UpdateConfig, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UpdateConfigTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `update_config`.
    pub fn id(&self) -> UpdateConfigIdUnique<'ctx> {
        UpdateConfigIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UpdateConfigIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<UpdateConfig> {
        self.imp.find(col_val)
    }
}
