// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::internal_entity_position_type::InternalEntityPosition;
use super::stdb_transform_type::StdbTransform;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `internal_entity_position`.
///
/// Obtain a handle from the [`InternalEntityPositionTableAccess::internal_entity_position`] method on [`super::RemoteTables`],
/// like `ctx.db.internal_entity_position()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.internal_entity_position().on_insert(...)`.
pub struct InternalEntityPositionTableHandle<'ctx> {
    imp: __sdk::TableHandle<InternalEntityPosition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `internal_entity_position`.
///
/// Implemented for [`super::RemoteTables`].
pub trait InternalEntityPositionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`InternalEntityPositionTableHandle`], which mediates access to the table `internal_entity_position`.
    fn internal_entity_position(&self) -> InternalEntityPositionTableHandle<'_>;
}

impl InternalEntityPositionTableAccess for super::RemoteTables {
    fn internal_entity_position(&self) -> InternalEntityPositionTableHandle<'_> {
        InternalEntityPositionTableHandle {
            imp: self
                .imp
                .get_table::<InternalEntityPosition>("internal_entity_position"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct InternalEntityPositionInsertCallbackId(__sdk::CallbackId);
pub struct InternalEntityPositionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for InternalEntityPositionTableHandle<'ctx> {
    type Row = InternalEntityPosition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InternalEntityPosition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = InternalEntityPositionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InternalEntityPositionInsertCallbackId {
        InternalEntityPositionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: InternalEntityPositionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = InternalEntityPositionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InternalEntityPositionDeleteCallbackId {
        InternalEntityPositionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: InternalEntityPositionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<InternalEntityPosition>("internal_entity_position");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<InternalEntityPosition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<InternalEntityPosition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `internal_entity_position`,
/// which allows point queries on the field of the same name
/// via the [`InternalEntityPositionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.internal_entity_position().id().find(...)`.
pub struct InternalEntityPositionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<InternalEntityPosition, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> InternalEntityPositionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `internal_entity_position`.
    pub fn id(&self) -> InternalEntityPositionIdUnique<'ctx> {
        InternalEntityPositionIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> InternalEntityPositionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<InternalEntityPosition> {
        self.imp.find(col_val)
    }
}
