// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::stdb_position_type::StdbPosition;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `stdb_position`.
///
/// Obtain a handle from the [`StdbPositionTableAccess::stdb_position`] method on [`super::RemoteTables`],
/// like `ctx.db.stdb_position()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.stdb_position().on_insert(...)`.
pub struct StdbPositionTableHandle<'ctx> {
    imp: __sdk::TableHandle<StdbPosition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `stdb_position`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StdbPositionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StdbPositionTableHandle`], which mediates access to the table `stdb_position`.
    fn stdb_position(&self) -> StdbPositionTableHandle<'_>;
}

impl StdbPositionTableAccess for super::RemoteTables {
    fn stdb_position(&self) -> StdbPositionTableHandle<'_> {
        StdbPositionTableHandle {
            imp: self.imp.get_table::<StdbPosition>("stdb_position"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StdbPositionInsertCallbackId(__sdk::CallbackId);
pub struct StdbPositionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for StdbPositionTableHandle<'ctx> {
    type Row = StdbPosition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StdbPosition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StdbPositionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StdbPositionInsertCallbackId {
        StdbPositionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StdbPositionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StdbPositionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StdbPositionDeleteCallbackId {
        StdbPositionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StdbPositionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<StdbPosition>("stdb_position");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<StdbPosition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<StdbPosition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
