// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::entity_position_hr_type::EntityPositionHr;
use super::stdb_transform_type::StdbTransform;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `entity_position_hr`.
///
/// Obtain a handle from the [`EntityPositionHrTableAccess::entity_position_hr`] method on [`super::RemoteTables`],
/// like `ctx.db.entity_position_hr()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.entity_position_hr().on_insert(...)`.
pub struct EntityPositionHrTableHandle<'ctx> {
    imp: __sdk::TableHandle<EntityPositionHr>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `entity_position_hr`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EntityPositionHrTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EntityPositionHrTableHandle`], which mediates access to the table `entity_position_hr`.
    fn entity_position_hr(&self) -> EntityPositionHrTableHandle<'_>;
}

impl EntityPositionHrTableAccess for super::RemoteTables {
    fn entity_position_hr(&self) -> EntityPositionHrTableHandle<'_> {
        EntityPositionHrTableHandle {
            imp: self.imp.get_table::<EntityPositionHr>("entity_position_hr"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EntityPositionHrInsertCallbackId(__sdk::CallbackId);
pub struct EntityPositionHrDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EntityPositionHrTableHandle<'ctx> {
    type Row = EntityPositionHr;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EntityPositionHr> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EntityPositionHrInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityPositionHrInsertCallbackId {
        EntityPositionHrInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EntityPositionHrInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EntityPositionHrDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityPositionHrDeleteCallbackId {
        EntityPositionHrDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EntityPositionHrDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EntityPositionHr>("entity_position_hr");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<EntityPositionHr>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EntityPositionHr>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `entity_position_hr`,
/// which allows point queries on the field of the same name
/// via the [`EntityPositionHrIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.entity_position_hr().id().find(...)`.
pub struct EntityPositionHrIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EntityPositionHr, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EntityPositionHrTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `entity_position_hr`.
    pub fn id(&self) -> EntityPositionHrIdUnique<'ctx> {
        EntityPositionHrIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EntityPositionHrIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<EntityPositionHr> {
        self.imp.find(col_val)
    }
}
