// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::entity_position_lr_type::EntityPositionLr;
use super::stdb_transform_type::StdbTransform;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `entity_position_lr`.
///
/// Obtain a handle from the [`EntityPositionLrTableAccess::entity_position_lr`] method on [`super::RemoteTables`],
/// like `ctx.db.entity_position_lr()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.entity_position_lr().on_insert(...)`.
pub struct EntityPositionLrTableHandle<'ctx> {
    imp: __sdk::TableHandle<EntityPositionLr>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `entity_position_lr`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EntityPositionLrTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EntityPositionLrTableHandle`], which mediates access to the table `entity_position_lr`.
    fn entity_position_lr(&self) -> EntityPositionLrTableHandle<'_>;
}

impl EntityPositionLrTableAccess for super::RemoteTables {
    fn entity_position_lr(&self) -> EntityPositionLrTableHandle<'_> {
        EntityPositionLrTableHandle {
            imp: self.imp.get_table::<EntityPositionLr>("entity_position_lr"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EntityPositionLrInsertCallbackId(__sdk::CallbackId);
pub struct EntityPositionLrDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EntityPositionLrTableHandle<'ctx> {
    type Row = EntityPositionLr;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EntityPositionLr> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EntityPositionLrInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityPositionLrInsertCallbackId {
        EntityPositionLrInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EntityPositionLrInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EntityPositionLrDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityPositionLrDeleteCallbackId {
        EntityPositionLrDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EntityPositionLrDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EntityPositionLr>("entity_position_lr");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<EntityPositionLr>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EntityPositionLr>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `entity_position_lr`,
/// which allows point queries on the field of the same name
/// via the [`EntityPositionLrIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.entity_position_lr().id().find(...)`.
pub struct EntityPositionLrIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EntityPositionLr, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EntityPositionLrTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `entity_position_lr`.
    pub fn id(&self) -> EntityPositionLrIdUnique<'ctx> {
        EntityPositionLrIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EntityPositionLrIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<EntityPositionLr> {
        self.imp.find(col_val)
    }
}
