// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::roles_type::Roles;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `roles`.
///
/// Obtain a handle from the [`RolesTableAccess::roles`] method on [`super::RemoteTables`],
/// like `ctx.db.roles()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.roles().on_insert(...)`.
pub struct RolesTableHandle<'ctx> {
    imp: __sdk::TableHandle<Roles>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `roles`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RolesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RolesTableHandle`], which mediates access to the table `roles`.
    fn roles(&self) -> RolesTableHandle<'_>;
}

impl RolesTableAccess for super::RemoteTables {
    fn roles(&self) -> RolesTableHandle<'_> {
        RolesTableHandle {
            imp: self.imp.get_table::<Roles>("roles"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RolesInsertCallbackId(__sdk::CallbackId);
pub struct RolesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RolesTableHandle<'ctx> {
    type Row = Roles;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Roles> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RolesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RolesInsertCallbackId {
        RolesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RolesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RolesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RolesDeleteCallbackId {
        RolesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RolesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Roles>("roles");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}
pub struct RolesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RolesTableHandle<'ctx> {
    type UpdateCallbackId = RolesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RolesUpdateCallbackId {
        RolesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RolesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Roles>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Roles>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `identity` unique index on the table `roles`,
/// which allows point queries on the field of the same name
/// via the [`RolesIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.roles().identity().find(...)`.
pub struct RolesIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Roles, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RolesTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `roles`.
    pub fn identity(&self) -> RolesIdentityUnique<'ctx> {
        RolesIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RolesIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Roles> {
        self.imp.find(col_val)
    }
}
