// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetUserNameArgs {
    pub username: String,
}

impl From<SetUserNameArgs> for super::Reducer {
    fn from(args: SetUserNameArgs) -> Self {
        Self::SetUserName {
            username: args.username,
        }
    }
}

impl __sdk::InModule for SetUserNameArgs {
    type Module = super::RemoteModule;
}

pub struct SetUserNameCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_user_name`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_user_name {
    /// Request that the remote module invoke the reducer `set_user_name` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_set_user_name`] callbacks.
    fn set_user_name(&self, username: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `set_user_name`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SetUserNameCallbackId`] can be passed to [`Self::remove_on_set_user_name`]
    /// to cancel the callback.
    fn on_set_user_name(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> SetUserNameCallbackId;
    /// Cancel a callback previously registered by [`Self::on_set_user_name`],
    /// causing it not to run in the future.
    fn remove_on_set_user_name(&self, callback: SetUserNameCallbackId);
}

impl set_user_name for super::RemoteReducers {
    fn set_user_name(&self, username: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("set_user_name", SetUserNameArgs { username })
    }
    fn on_set_user_name(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> SetUserNameCallbackId {
        SetUserNameCallbackId(self.imp.on_reducer(
            "set_user_name",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SetUserName { username },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, username)
            }),
        ))
    }
    fn remove_on_set_user_name(&self, callback: SetUserNameCallbackId) {
        self.imp.remove_on_reducer("set_user_name", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `set_user_name`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_set_user_name {
    /// Set the call-reducer flags for the reducer `set_user_name` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn set_user_name(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_set_user_name for super::SetReducerFlags {
    fn set_user_name(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("set_user_name", flags);
    }
}
