// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::stdb_rotation_type::StdbRotation;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `stdb_rotation`.
///
/// Obtain a handle from the [`StdbRotationTableAccess::stdb_rotation`] method on [`super::RemoteTables`],
/// like `ctx.db.stdb_rotation()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.stdb_rotation().on_insert(...)`.
pub struct StdbRotationTableHandle<'ctx> {
    imp: __sdk::TableHandle<StdbRotation>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `stdb_rotation`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StdbRotationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StdbRotationTableHandle`], which mediates access to the table `stdb_rotation`.
    fn stdb_rotation(&self) -> StdbRotationTableHandle<'_>;
}

impl StdbRotationTableAccess for super::RemoteTables {
    fn stdb_rotation(&self) -> StdbRotationTableHandle<'_> {
        StdbRotationTableHandle {
            imp: self.imp.get_table::<StdbRotation>("stdb_rotation"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StdbRotationInsertCallbackId(__sdk::CallbackId);
pub struct StdbRotationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for StdbRotationTableHandle<'ctx> {
    type Row = StdbRotation;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StdbRotation> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StdbRotationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StdbRotationInsertCallbackId {
        StdbRotationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StdbRotationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StdbRotationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StdbRotationDeleteCallbackId {
        StdbRotationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StdbRotationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<StdbRotation>("stdb_rotation");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<StdbRotation>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<StdbRotation>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
