// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::stdb_position_type::StdbPosition;
use super::stdb_rotation_type::StdbRotation;
use super::stdb_transform_type::StdbTransform;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `stdb_transform`.
///
/// Obtain a handle from the [`StdbTransformTableAccess::stdb_transform`] method on [`super::RemoteTables`],
/// like `ctx.db.stdb_transform()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.stdb_transform().on_insert(...)`.
pub struct StdbTransformTableHandle<'ctx> {
    imp: __sdk::TableHandle<StdbTransform>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `stdb_transform`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StdbTransformTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StdbTransformTableHandle`], which mediates access to the table `stdb_transform`.
    fn stdb_transform(&self) -> StdbTransformTableHandle<'_>;
}

impl StdbTransformTableAccess for super::RemoteTables {
    fn stdb_transform(&self) -> StdbTransformTableHandle<'_> {
        StdbTransformTableHandle {
            imp: self.imp.get_table::<StdbTransform>("stdb_transform"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StdbTransformInsertCallbackId(__sdk::CallbackId);
pub struct StdbTransformDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for StdbTransformTableHandle<'ctx> {
    type Row = StdbTransform;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StdbTransform> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StdbTransformInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StdbTransformInsertCallbackId {
        StdbTransformInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StdbTransformInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StdbTransformDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StdbTransformDeleteCallbackId {
        StdbTransformDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StdbTransformDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<StdbTransform>("stdb_transform");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<StdbTransform>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<StdbTransform>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
