// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::update_position_timer_type::UpdatePositionTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateAllPositionsArgs {
    pub arg: UpdatePositionTimer,
}

impl From<UpdateAllPositionsArgs> for super::Reducer {
    fn from(args: UpdateAllPositionsArgs) -> Self {
        Self::UpdateAllPositions { arg: args.arg }
    }
}

impl __sdk::InModule for UpdateAllPositionsArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateAllPositionsCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_all_positions`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_all_positions {
    /// Request that the remote module invoke the reducer `update_all_positions` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_all_positions`] callbacks.
    fn update_all_positions(&self, arg: UpdatePositionTimer) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_all_positions`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateAllPositionsCallbackId`] can be passed to [`Self::remove_on_update_all_positions`]
    /// to cancel the callback.
    fn on_update_all_positions(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &UpdatePositionTimer) + Send + 'static,
    ) -> UpdateAllPositionsCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_all_positions`],
    /// causing it not to run in the future.
    fn remove_on_update_all_positions(&self, callback: UpdateAllPositionsCallbackId);
}

impl update_all_positions for super::RemoteReducers {
    fn update_all_positions(&self, arg: UpdatePositionTimer) -> __sdk::Result<()> {
        self.imp
            .call_reducer("update_all_positions", UpdateAllPositionsArgs { arg })
    }
    fn on_update_all_positions(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &UpdatePositionTimer) + Send + 'static,
    ) -> UpdateAllPositionsCallbackId {
        UpdateAllPositionsCallbackId(self.imp.on_reducer(
            "update_all_positions",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::UpdateAllPositions { arg },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, arg)
            }),
        ))
    }
    fn remove_on_update_all_positions(&self, callback: UpdateAllPositionsCallbackId) {
        self.imp
            .remove_on_reducer("update_all_positions", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_all_positions`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_all_positions {
    /// Set the call-reducer flags for the reducer `update_all_positions` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_all_positions(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_all_positions for super::SetReducerFlags {
    fn update_all_positions(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("update_all_positions", flags);
    }
}
